// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {serializer} from '../models';

export function Save():void;

export function Test(arg1:any):Promise<serializer.Response>;
