// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Test() {
  window['go']['proc']['ConnectProcess']['Test']();
}

export function Save() {
  window['go']['proc']['ConnectProcess']['Save']();
}
