// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Save() {
  window['go']['frontend']['Driver']['Save']();
}

export function Test() {
  window['go']['frontend']['Driver']['Test']();
}
