// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['bridge']['App']['Greet'](arg1);
}

export function DomReady(arg1) {
  window['go']['bridge']['App']['DomReady'](arg1);
}
