// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function List():Promise<any>;

export function Save(arg1:any):Promise<any>;

export function Test(arg1:any):Promise<any>;

export function Delete(arg1:any):Promise<any>;

export function Get(arg1:any):Promise<any>;
