// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['bridge']['Connections']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['bridge']['Connections']['Get'](arg1);
}

export function List() {
  return window['go']['bridge']['Connections']['List']();
}

export function Save(arg1) {
  return window['go']['bridge']['Connections']['Save'](arg1);
}

export function Test(arg1) {
  return window['go']['bridge']['Connections']['Test'](arg1);
}
