// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {serializer} from '../models';

export function Delete(arg1:{[key: string]: string}):Promise<serializer.Response>;

export function Get(arg1:{[key: string]: string}):Promise<serializer.Response>;

export function List():Promise<serializer.Response>;

export function Save(arg1:{[key: string]: string}):Promise<serializer.Response>;

export function Test(arg1:{[key: string]: any}):Promise<any>;
