// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {serializer} from '../models';

export function Refresh(arg1:string):void;

export function ServerVersion(arg1:bridge.DatabaseRequest):Promise<serializer.Response>;

export function Status(arg1:bridge.DatabaseRequest):Promise<serializer.Response>;

export function Structure(arg1:bridge.DatabaseRequest):Promise<any>;

export function Close(arg1:bridge.DatabaseKillRequest):void;

export function Ping(arg1:bridge.DatabaseRequest):Promise<serializer.Response>;
