// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Refresh(arg1) {
  window['go']['bridge']['DatabaseConnections']['Refresh'](arg1);
}

export function ServerVersion(arg1) {
  return window['go']['bridge']['DatabaseConnections']['ServerVersion'](arg1);
}

export function Status(arg1) {
  return window['go']['bridge']['DatabaseConnections']['Status'](arg1);
}

export function Structure(arg1) {
  return window['go']['bridge']['DatabaseConnections']['Structure'](arg1);
}

export function Close(arg1) {
  window['go']['bridge']['DatabaseConnections']['Close'](arg1);
}

export function Ping(arg1) {
  return window['go']['bridge']['DatabaseConnections']['Ping'](arg1);
}
