// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ping(arg1) {
  return window['go']['bridge']['DatabaseConnections']['Ping'](arg1);
}

export function Refresh(arg1) {
  window['go']['bridge']['DatabaseConnections']['Refresh'](arg1);
}

export function Structure(arg1, arg2) {
  return window['go']['bridge']['DatabaseConnections']['Structure'](arg1, arg2);
}
