// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {serializer} from '../models';

export function Status(arg1:bridge.DatabaseRequest):Promise<serializer.Response>;

export function Structure(arg1:bridge.DatabaseRequest):Promise<any>;

export function SyncModel(arg1:bridge.DatabaseRequest):Promise<serializer.Response>;

export function Disconnect(arg1:bridge.DatabaseRequest):Promise<serializer.Response>;

export function Ping(arg1:bridge.DatabaseRequest):Promise<serializer.Response>;

export function Refresh(arg1:bridge.DatabaseKeepOpenRequest):Promise<serializer.Response>;

export function ServerVersion(arg1:bridge.DatabaseRequest):Promise<serializer.Response>;
