// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function Ping(arg1:bridge.DatabasePingRequest):Promise<any>;

export function Refresh(arg1:string):void;

export function Structure(arg1:string,arg2:string):Promise<any>;
