// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDatabases(arg1) {
  return window['go']['bridge']['ServerConnections']['ListDatabases'](arg1);
}

export function Ping(arg1) {
  return window['go']['bridge']['ServerConnections']['Ping'](arg1);
}
