// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {serializer} from '../models';

export function Refresh(arg1:bridge.ServerRefreshRequest):Promise<serializer.Response>;

export function Reset():Promise<serializer.Response>;

export function ServerStatus():Promise<any>;

export function Close(arg1:string,arg2:boolean):void;

export function ListDatabases(arg1:any):Promise<serializer.Response>;

export function Ping(arg1:Array<string>):Promise<serializer.Response>;
