// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function Close(arg1:string,arg2:boolean):void;

export function ListDatabases(arg1:string):Promise<any>;

export function Ping(arg1:Array<string>):Promise<any>;

export function Refresh(arg1:bridge.ServerRefreshRequest):Promise<any>;

export function ServerStatus():Promise<any>;
