// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Save(arg1:any):Promise<any>;

export function ServerStatus():void;

export function Test(arg1:any):Promise<any>;

export function List():Promise<any>;
