// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Test(arg1) {
  return window['go']['bridge']['Connections']['Test'](arg1);
}

export function Save() {
  window['go']['bridge']['Connections']['Save']();
}
