// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Save(arg1) {
  return window['go']['bridge']['Connections']['Save'](arg1);
}

export function ServerStatus() {
  window['go']['bridge']['Connections']['ServerStatus']();
}

export function Test(arg1) {
  return window['go']['bridge']['Connections']['Test'](arg1);
}

export function List() {
  return window['go']['bridge']['Connections']['List']();
}
